//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server.Clients
{
    using System;
    using Beamable.Platform.SDK;
    using Beamable.Server;
    
    
    /// <summary> A generated client for <see cref="Beamable.TestService.TestService"/> </summary
    public sealed class TestServiceClient : MicroserviceClient, Beamable.Common.IHaveServiceName
    {
        
        public TestServiceClient(BeamContext context = null) : 
                base(context)
        {
        }
        
        public TestServiceClient(Beamable.Common.Dependencies.IDependencyProvider provider) : 
                base(provider)
        {
        }
        
        public string ServiceName
        {
            get
            {
                return "TestService";
            }
        }
        
        /// <summary>
        /// Call the Add method on the TestService microservice
        /// <see cref="Beamable.TestService.TestService.Add"/>
        /// </summary>
        public Beamable.Common.Promise<int> Add(int a, int b)
        {
            object raw_a = a;
            object raw_b = b;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("a", raw_a);
            serializedFields.Add("b", raw_b);
            return this.Request<int>("TestService", "Add", serializedFields);
        }
    }
    
    internal sealed class MicroserviceParametersTestServiceClient
    {
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_Int32 : MicroserviceClientDataWrapper<int>
        {
        }
    }
    
    [BeamContextSystemAttribute()]
    public static class ExtensionsForTestServiceClient
    {
        
        [Beamable.Common.Dependencies.RegisterBeamableDependenciesAttribute(50, Beamable.Common.Dependencies.RegistrationOrigin.EDITOR | Beamable.Common.Dependencies.RegistrationOrigin.RUNTIME)]
        public static void RegisterService(Beamable.Common.Dependencies.IDependencyBuilder builder)
        {
            System.Func<Beamable.Common.Dependencies.IDependencyProvider, TestServiceClient> factory = p => new TestServiceClient(p);
            builder.AddScoped<TestServiceClient>(factory);
        }
        
        public static TestServiceClient TestService(this Beamable.Server.MicroserviceClients clients)
        {
            return clients.GetClient<TestServiceClient>();
        }
    }
}
